import { db } from "@/db";
import { bookings, parkingSpaces, walletTransactions } from "@/db/schema";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { hashSync } from "bcryptjs";

export async function ensureParkmeSeeded() {
  const [existing] = await db.select({ id: users.id }).from(users).limit(1);
  if (existing) return;

  const passwordHash = hashSync("demo1234", 10);
  const [demoUser] = await db
    .insert(users)
    .values({
      email: "miki@parkme.et",
      name: "Miki Tadesse",
      passwordHash,
      phone: "+251911234567",
    })
    .onConflictDoNothing({ target: users.email })
    .returning();

  let userId: string;
  if (demoUser) {
    userId = demoUser.id;
  } else {
    const [existingUser] = await db.select({ id: users.id }).from(users).where(eq(users.email, "miki@parkme.et")).limit(1);
    userId = existingUser!.id;
  }

  await db
    .insert(parkingSpaces)
    .values([
      {
        slug: "unity-park-garage",
        name: "Unity Park Garage",
        address: "Arat Kilo, Addis Ababa",
        neighborhood: "Arat Kilo",
        kind: "Best value",
        tone: "sage",
        priceHourlyEtb: 35,
        ratingTenths: 49,
        availableSpots: 12,
        totalSpots: 36,
        hostName: "Miki Tadesse",
        lat: 9.0369,
        lng: 38.7465,
      },
      {
        slug: "bole-medhanialem",
        name: "Bole Medhanialem",
        address: "Bole Road, Addis Ababa",
        neighborhood: "Bole",
        kind: "Covered",
        tone: "sand",
        priceHourlyEtb: 45,
        ratingTenths: 48,
        availableSpots: 6,
        totalSpots: 18,
        hostName: "Miki Tadesse",
        lat: 9.0120,
        lng: 38.7895,
      },
      {
        slug: "meskel-square-lot",
        name: "Meskel Square Lot",
        address: "Meskel Square, Addis Ababa",
        neighborhood: "Meskel Square",
        kind: "Open air",
        tone: "rose",
        priceHourlyEtb: 30,
        ratingTenths: 47,
        availableSpots: 18,
        totalSpots: 50,
        hostName: "Miki Tadesse",
        lat: 9.0113,
        lng: 38.7614,
      },
      {
        slug: "mexico-square-space-4",
        name: "Mexico Square Space #4",
        address: "Churchill Avenue, Addis Ababa",
        neighborhood: "Mexico Square",
        kind: "Covered",
        tone: "sand",
        priceHourlyEtb: 35,
        ratingTenths: 46,
        availableSpots: 4,
        totalSpots: 10,
        hostName: "Miki Tadesse",
        lat: 9.0285,
        lng: 38.7578,
      },
      {
        slug: "edna-mall-parking",
        name: "Edna Mall Parking",
        address: "Bole Road, Addis Ababa",
        neighborhood: "Bole",
        kind: "Covered",
        tone: "sage",
        priceHourlyEtb: 50,
        ratingTenths: 47,
        availableSpots: 8,
        totalSpots: 24,
        hostName: "Miki Tadesse",
        lat: 9.0058,
        lng: 38.7833,
      },
      {
        slug: "piassa-parking-lot",
        name: "Piassa Parking Lot",
        address: "Piazza, Addis Ababa",
        neighborhood: "Piassa",
        kind: "Open air",
        tone: "rose",
        priceHourlyEtb: 25,
        ratingTenths: 44,
        availableSpots: 15,
        totalSpots: 30,
        hostName: "Miki Tadesse",
        lat: 9.0353,
        lng: 38.7470,
      },
      {
        slug: "merkato-parking-hub",
        name: "Merkato Parking Hub",
        address: "Merkato, Addis Ababa",
        neighborhood: "Merkato",
        kind: "Open air",
        tone: "sand",
        priceHourlyEtb: 20,
        ratingTenths: 42,
        availableSpots: 25,
        totalSpots: 60,
        hostName: "Miki Tadesse",
        lat: 9.0153,
        lng: 38.7458,
      },
      {
        slug: "bole-road-garage",
        name: "Bole Road Garage",
        address: "Bole Road, Addis Ababa",
        neighborhood: "Bole",
        kind: "Covered",
        tone: "sage",
        priceHourlyEtb: 45,
        ratingTenths: 48,
        availableSpots: 10,
        totalSpots: 30,
        hostName: "Miki Tadesse",
        lat: 9.0098,
        lng: 38.7790,
      },
      {
        slug: "kazanchis-business-parking",
        name: "Kazanchis Business Parking",
        address: "Kazanchis, Addis Ababa",
        neighborhood: "Kazanchis",
        kind: "Covered",
        tone: "rose",
        priceHourlyEtb: 40,
        ratingTenths: 46,
        availableSpots: 8,
        totalSpots: 20,
        hostName: "Miki Tadesse",
        lat: 9.0167,
        lng: 38.7617,
      },
      {
        slug: "churchill-avenue-lot",
        name: "Churchill Avenue Lot",
        address: "Churchill Avenue, Addis Ababa",
        neighborhood: "Arat Kilo",
        kind: "Open air",
        tone: "sand",
        priceHourlyEtb: 30,
        ratingTenths: 45,
        availableSpots: 14,
        totalSpots: 35,
        hostName: "Miki Tadesse",
        lat: 9.0327,
        lng: 38.7503,
      },
      {
        slug: "lideta-parking-space",
        name: "Lideta Parking Space",
        address: "Lideta, Addis Ababa",
        neighborhood: "Lideta",
        kind: "Open air",
        tone: "sage",
        priceHourlyEtb: 25,
        ratingTenths: 43,
        availableSpots: 12,
        totalSpots: 28,
        hostName: "Miki Tadesse",
        lat: 9.0240,
        lng: 38.7505,
      },
      {
        slug: "summit-view-parking",
        name: "Summit View Parking",
        address: "Summit, Addis Ababa",
        neighborhood: "Summit",
        kind: "Open air",
        tone: "rose",
        priceHourlyEtb: 20,
        ratingTenths: 41,
        availableSpots: 20,
        totalSpots: 40,
        hostName: "Miki Tadesse",
        lat: 9.0030,
        lng: 38.7445,
      },
      {
        slug: "6-kilo-campus-parking",
        name: "6 Kilo Campus Parking",
        address: "6 Kilo, Addis Ababa",
        neighborhood: "6 Kilo",
        kind: "Open air",
        tone: "sand",
        priceHourlyEtb: 15,
        ratingTenths: 44,
        availableSpots: 30,
        totalSpots: 50,
        hostName: "Miki Tadesse",
        lat: 9.0370,
        lng: 38.7622,
      },
      {
        slug: "gullele-botanical-parking",
        name: "Gullele Botanical Parking",
        address: "Gullele, Addis Ababa",
        neighborhood: "Gullele",
        kind: "Open air",
        tone: "sage",
        priceHourlyEtb: 20,
        ratingTenths: 45,
        availableSpots: 18,
        totalSpots: 35,
        hostName: "Miki Tadesse",
        lat: 9.0510,
        lng: 38.7380,
      },
      {
        slug: "akaki-parking-lot",
        name: "Akaki Parking Lot",
        address: "Akaki, Addis Ababa",
        neighborhood: "Akaki",
        kind: "Open air",
        tone: "sand",
        priceHourlyEtb: 15,
        ratingTenths: 40,
        availableSpots: 22,
        totalSpots: 45,
        hostName: "Miki Tadesse",
        lat: 8.9950,
        lng: 38.7570,
      },
      {
        slug: "kality-industrial-parking",
        name: "Kality Industrial Parking",
        address: "Kality, Addis Ababa",
        neighborhood: "Kality",
        kind: "Open air",
        tone: "rose",
        priceHourlyEtb: 15,
        ratingTenths: 39,
        availableSpots: 28,
        totalSpots: 50,
        hostName: "Miki Tadesse",
        lat: 8.9880,
        lng: 38.7625,
      },
      {
        slug: "mexico-supermarket-parking",
        name: "Mexico Supermarket Parking",
        address: "Mexico Area, Addis Ababa",
        neighborhood: "Mexico Square",
        kind: "Covered",
        tone: "sage",
        priceHourlyEtb: 35,
        ratingTenths: 46,
        availableSpots: 6,
        totalSpots: 15,
        hostName: "Miki Tadesse",
        lat: 9.0268,
        lng: 38.7595,
      },
      {
        slug: "haya-hulet-parking",
        name: "Haya Hulet Parking",
        address: "Haya Hulet, Addis Ababa",
        neighborhood: "Haya Hulet",
        kind: "Covered",
        tone: "sand",
        priceHourlyEtb: 35,
        ratingTenths: 45,
        availableSpots: 9,
        totalSpots: 22,
        hostName: "Miki Tadesse",
        lat: 9.0290,
        lng: 38.7410,
      },
      {
        slug: "bole-medhanialem-2",
        name: "Bole Medhanialem II",
        address: "Bole Medhanialem, Addis Ababa",
        neighborhood: "Bole",
        kind: "Covered",
        tone: "rose",
        priceHourlyEtb: 50,
        ratingTenths: 49,
        availableSpots: 5,
        totalSpots: 16,
        hostName: "Miki Tadesse",
        lat: 9.0115,
        lng: 38.7910,
      },
      {
        slug: "bole-atlas-parking",
        name: "Bole Atlas Parking",
        address: "Bole Atlas, Addis Ababa",
        neighborhood: "Bole",
        kind: "Covered",
        tone: "sage",
        priceHourlyEtb: 45,
        ratingTenths: 47,
        availableSpots: 7,
        totalSpots: 20,
        hostName: "Miki Tadesse",
        lat: 9.0045,
        lng: 38.7875,
      },
      {
        slug: "old-airport-parking",
        name: "Old Airport Parking",
        address: "Old Airport Area, Addis Ababa",
        neighborhood: "Bole",
        kind: "Open air",
        tone: "sand",
        priceHourlyEtb: 30,
        ratingTenths: 44,
        availableSpots: 16,
        totalSpots: 35,
        hostName: "Miki Tadesse",
        lat: 9.0125,
        lng: 38.7750,
      },
      {
        slug: "arada-parking-hub",
        name: "Arada Parking Hub",
        address: "Arada, Addis Ababa",
        neighborhood: "Arada",
        kind: "Open air",
        tone: "rose",
        priceHourlyEtb: 25,
        ratingTenths: 43,
        availableSpots: 14,
        totalSpots: 30,
        hostName: "Miki Tadesse",
        lat: 9.0295,
        lng: 38.7540,
      },
      {
        slug: "shiro-meda-parking",
        name: "Shiro Meda Parking",
        address: "Shiro Meda, Addis Ababa",
        neighborhood: "Shiro Meda",
        kind: "Open air",
        tone: "sage",
        priceHourlyEtb: 20,
        ratingTenths: 42,
        availableSpots: 18,
        totalSpots: 35,
        hostName: "Miki Tadesse",
        lat: 9.0450,
        lng: 38.7530,
      },
      {
        slug: "tor-hayloch-parking",
        name: "Tor Hayloch Parking",
        address: "Tor Hayloch, Addis Ababa",
        neighborhood: "Nifas Silk",
        kind: "Open air",
        tone: "sand",
        priceHourlyEtb: 20,
        ratingTenths: 41,
        availableSpots: 20,
        totalSpots: 40,
        hostName: "Miki Tadesse",
        lat: 9.0010,
        lng: 38.7680,
      },
      {
        slug: "megenagna-parking",
        name: "Megenagna Parking",
        address: "Megenagna, Addis Ababa",
        neighborhood: "Megenagna",
        kind: "Covered",
        tone: "rose",
        priceHourlyEtb: 40,
        ratingTenths: 47,
        availableSpots: 8,
        totalSpots: 22,
        hostName: "Miki Tadesse",
        lat: 9.0170,
        lng: 38.7830,
      },
      {
        slug: "gerji-parking-lot",
        name: "Gerji Parking Lot",
        address: "Gerji, Addis Ababa",
        neighborhood: "Bole",
        kind: "Open air",
        tone: "sage",
        priceHourlyEtb: 30,
        ratingTenths: 44,
        availableSpots: 15,
        totalSpots: 30,
        hostName: "Miki Tadesse",
        lat: 9.0075,
        lng: 38.7950,
      },
    ])
    .onConflictDoNothing({ target: parkingSpaces.slug });

  await db
    .insert(walletTransactions)
    .values({
      reference: "seed-wallet-opening-balance",
      userId,
      type: "deposit",
      amountEtb: 500,
      provider: "telebirr",
      note: "ParkmeWallet opening balance",
    })
    .onConflictDoNothing({ target: walletTransactions.reference });

  const [unityPark] = await db
    .select({ id: parkingSpaces.id })
    .from(parkingSpaces)
    .where(eq(parkingSpaces.slug, "unity-park-garage"))
    .limit(1);

  if (!unityPark) return;

  const now = new Date();
  const start = new Date(now.getTime() - 78 * 60 * 1000);
  const end = new Date(now.getTime() + 42 * 60 * 1000);
  const today = now.toISOString().slice(0, 10);

  await db
    .insert(bookings)
    .values({
      reference: "seed-active-unity-pass",
      userId,
      parkingSpaceId: unityPark.id,
      parkingDate: today,
      startAt: start,
      endAt: end,
      durationHours: 2,
      spaceLabel: "B · 27",
      status: "active",
      paymentMethod: "wallet",
      amountEtb: 70,
      gateCode: "4826",
    })
    .onConflictDoNothing({ target: bookings.reference });
}

export const DEMO_USER_EMAIL = "miki@parkme.et";
